sudo: required
language: generic
services:
- docker
env:
  matrix:
  - HHVM_VERSION=latest
  - secure: f51EctIRp3na/DYiKfCZyANLjRr5ph7lXpCT6HWf6ueY1DhKoHnw5OpVtfcQiwviNmSuRbvr7gOYqvSRJsVrj1WQ1HDAtsE+K44MMhHsbqpctH689rj4mflIVs6IDlaIOVs6ubykBkzv5FaXodsBPe5q5NKjbBN3w8AZJxsHHGmlxl17jHr+E/HWrWCABN3oG2HwiZVm73sePY4UjwtTdpO26FfqNrauOT6OlA3i+4g0jARsOgKlTBM9N4cpbYoXQeRba//DCn14NAl9yqupFFOFJ1grLaE+dGnDH6sQyUxOaDZbMA4xsxxUFcmcfYgAzNYQ1n2RIBe8kPDAkdgWc4wn8j6IP2Ltodud+4H98HtoLXo8thnI3EKqSi9Wzk/JkNjuaPmg5QOAW6ettWTIXKnqdc91lu7dlxD6oC19laOB3Rr89v0zZ+IC1r9N3GuMG4WNNBVKPwIJEWKdqqcHQio9tf2AlzG35/grupJ4USGZgk0zuIR2kcAL5XUDBCjvOUWB+40B6sZKZfmi08nsgMvfoHvSz/EQd+1wK9sq8W0jL2pHZgLZ/I63GJjR2V0fER6DWxfkqLqVacazqadm7IUYtEmsTHy6QUDKwooaVdKDlvB4YFcIRqn8n2fT6nysSbEunNDMIT714bcxVrl4TPjjnX7nvoHekbhgu0uylDg=
install:
- docker pull zerodiv/hhvm:$HHVM_VERSION
script:
- docker run -it -e GITHUB_TOKEN=$GITHUB_TOKEN -v $(pwd):/var/source zerodiv/hhvm:$HHVM_VERSION
  /var/source/.build.sh
